# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: contact-create-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "amqps://admin:admin@rabbitmq:5672/"
  RabbitMq__Queue: "contact.create"
  
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-create-deployment
  labels:
    app: contact-create
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-create
  template:
    metadata:
      labels:
        app: contact-create
    spec:
      containers:
        - name: contact-create-container
          image: gugol94/fiapcontacts-create:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: contact-create-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
