apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-create-deployment
  labels:
    app: contact-create
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-create
  template:
    metadata:
      labels:
        app: contact-create
    spec:
      containers:
        - name: contact-create-container
          image: gugol94/fiapcontacts-create:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: contact-create-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "110m"
            limits:
              memory: "256Mi"
              cpu: "150m"
