apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fiapcontacts-create-replicaset
  labels:
    app: fiapcontacts-create
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fiapcontacts-create
  template:
    metadata:
      labels:
        app: fiapcontacts-create
    spec:
      containers:
        - name: fiapcontacts-create-container
          image: gugol94/fiapcontacts-create:latest
          ports:
            - containerPort: 80
